[workspace]
channels = ["knime", "conda-forge"]
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]

[tasks]

[dependencies]
python = "3.11.*"
knime-extension = "*"
knime-python-base = "*"
pydoe3 = ">=1.4.0,<2"
scipy = ">=1.16.2,<2"
simpy = ">=4.1.1,<5"

[feature.build.dependencies]
python = "3.9.*"
knime-extension-bundling = "5.11.*"

[feature.build.tasks]
build = "python ./.pixi/envs/build/Scripts/build_python_extension.py-script.py --disable-strict-enforcement . ./local-update-site"

[environments]
build = {features = ["build"], no-default-feature = true}

